name: CI - Merge Main

on:
  pull_request:
    branches:
      - main

jobs:
  ci-checks:
    name: CI Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Node dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-node-modules-${{ hashFiles('web/package-lock.json') }}
          path: |
            web/node_modules

      - name: Cache Rust dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-rust-${{ hashFiles('api/Cargo.lock') }}
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            api/target

      - name: Setup Project
        run: make setup

      - name: Install Dependencies
        run: make install

      - name: Run Checks
        run: make check

      - name: Run Tests
        run: make test

      - name: Run Build
        run: make build
